name: Build release zip

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          # Navigate to the WoocoManage directory
          cd WoocoManage
          # Run necessary build steps like installing dependencies, building the project, etc.
          composer install --no-dev
          npm install
          npm run build

      - name: Generate zip
        run: |
          # Navigate back to the main directory
          cd ${{ github.workspace }}
          # Create a zip file containing the built files from the 'dist' directory
          zip -r woocomanage.zip .

      - name: Upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: WooCoManage
          path: ${{ github.workspace }}/woocomanage.zip
