name: Build release zip

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          # Navigate to the WoocoManage directory
          cd WooCoManage
          # Run necessary build steps like installing dependencies, building the project, etc.
          composer install --no-dev
          npm install
          npm run build

      - name: Making redy to Generate zip
        run: |
          # Navigate back to the main directory
          cd ${{ github.workspace }}
          # Create a temporary directory to copy files without altering them
          mkdir -p wooco/WooComanage
          # Copy necessary files and folders to the temporary directory
          cp -r WooCoManage/index.php WooCoManage/templates WooCoManage/uninstall.php WooCoManage/includes WooCoManage/assets WooCoManage/woocomanage.php WooCoManage/build wooco/WooComanage/

          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/wooco/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         

      - name: Upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: WooCoManage
          path: ${{ github.workspace }}/wooco
         
