name: Upload Artifact to Google Drive

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          # Navigate to the WoocoManage directory
          cd WooCoManage
          # Run necessary build steps like installing dependencies, building the project, etc.
          composer install --no-dev
          npm install
          npm run build

      - name: Making ready to Generate zip
        run: |
          # Navigate back to the main directory
          cd ${{ github.workspace }}
          # Create a temporary directory to copy files without altering them
          mkdir WooCo
          # Copy necessary files and folders to the temporary directory
          cp -r WooCoManage/index.php WooCoManage/templates WooCoManage/uninstall.php WooCoManage/includes WooCoManage/assets WooCoManage/woocomanage.php WooCoManage/build WooCo/
          # Create a zip file in the same directory
          zip -r WoocoManage.zip WooCo

        
      - name: Install mega-cmd
        run: apt-get update && apt-get install -y mega-cmd

      # You may need to manually authenticate with `mega-login` first, 
      # and then omit this step in subsequent workflow runs
      - name: Login to MEGA
        run: mega-login fonavo1244@nimadir.com Wooco123456789

      - name: Upload file to MEGA
        run: mega-put ${{ github.workspace }}/WoocoManage.zip /cXVzCZrB/
